### PR TITLE
Fix: 255 Fixed inconsistency in EvalAI description

### PR DESCRIPTION
**Pull request by jayaike**
Fixes # https://github.com/Cloud-CV/EvalAI-ngx/issues/255

Changed wording to remove inconsistency

### CODE REVIEW

**Comment by krtkvrm** [comment]
Thanks for the fix!

**Review by krtkvrm — APPROVED** [review]

**Comment by jayaike** [comment]
Anytime

**Comment by jayaike** [comment]
I think you should also take a look at https://github.com/Cloud-CV/EvalAI-ngx/pull/256

**Comment by jayaike** [comment]
@vkartik97

**Comment by RishabhJain2018** [comment]
Hi, @nsjcorps Thanks for the suggestion. Please read this: https://writingexplained.org/state-of-the-art-vs-state-of-the-art. It isn't a typo.
I'm closing this pull request. Feel free to open it if you have suggestions.

**Pull request closed without merging**
