### PR TITLE
Fix #35: Changed git clone statement in readme

### LINKED ISSUE #35: Git clone statement error
## I'm submitting a

(Check one with "x" from given options)
- [X] Bug report
- [ ] Feature request

## Current behavior
On using ``git clone git@github.com:Cloud-CV/EvalAI-ngx.git`` it gives an error regarding access rights

## Expected behavior
Change the statement to ``git clone https://github.com/Cloud-CV/EvalAI-ngx``

I would like to work on this

### PR DESCRIPTION
**Pull request by S2606**
Fixes #35

### CODE REVIEW

**Comment by S2606** [comment]
@aka-jain Please review

**Review by spyshiv — CHANGES_REQUESTED** [review]
Please refer to conversation of issue #35 and do the required changes

**Comment by S2606** [comment]
@spyshiv Please Review

**Comment by xamfy** [comment]
test is failing probably because of old version of chrome @aka-jain @spyshiv 
should I send a patch?

**Comment by spyshiv** [comment]
@S2606
Current behaviour is not looking perfect
screenshot from 2018-03-04 18 44 02


Suggestion: You can update like this using blockquotes
screenshot from 2018-03-04 18 37 08
ps: it's just a suggestion

**Comment by spyshiv** [comment]
@S2606 Any update on this?

**Comment by aka-jain** [comment]
@spyshiv Closing this PR as there is no activity on this.

**Pull request closed without merging**
