### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by Suryansh5545**
Replaced Cloud-CV with YOUR-USERNAME. As the person submitting the code will be first pushing it into his own repo first instead of evalai main repo

### CODE REVIEW

**Comment by drepram** [comment]
Why is it called `Updated CONTRIBUTING.md` instead of just `CONTRIBUTING.md`?

**Comment by Suryansh5545** [comment]
I don't know this I just updated url

**Comment by Suryansh5545** [comment]
Maybe this is for some other purpose

**Comment by nikochiko** [comment]
@Suryansh5545 I don't think this is a typo. The command is intended to keep
the origin branch in touch with the updates going on in the main
Cloud-CV/EvalAI repo.

**Comment by Suryansh5545** [comment]
@nikochiko The line I have edited is about adding a remote to submit the code . So it is quite obvious that the user will need to first push it on his own repo instead of adding the main EvalAI-ngx repo . On which he wouldn't have a write access

**Comment by nikochiko** [comment]
@Suryansh5545 I think you misunderstood it there. The *branch* we are creating *is* to make changes on it (and maybe, submit the code). But, the upstream we are adding here is so that our fork remains in sync with the main master from Cloud-CV. 
So, if you have already forked, and already checked out the branch you want to work on, you can run this command and anytime an update is made on Cloud-CV:master, you can fetch or pull it instantly. 
You can refer to this guide: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork

**Comment by Suryansh5545** [comment]
Yea you are right . I misunderstood it

**Pull request closed without merging**
