### PR TITLE
Added Not-Found Component for invalid paths

### PR DESCRIPTION
**Pull request by pavanrkadave**
Fixes #

#### Changes proposed in this pull request:

-

- Link to live demo: http://pr-XXX-evalai.surge.sh 

-

### CODE REVIEW

**Comment by pavanrkadave** [comment]
Hi, @live-wire can you help me with this PR?

**Comment by live-wire** [comment]
Hi @pavanrkadave,
Sorry about the delay. Were you able to get it up and running on your local machine ? 😄
Also, looks like the Travis Build is failing. Try to get a green light on this PR ?

**Comment by pavanrkadave** [comment]
Yes! It was working on my local, can you tell me the possible problems with regards to Travis build failure?

**Comment by live-wire** [comment]
- Did you run the tests on your local ?
- Did you see the travis logs ?
Please go through the [README](https://github.com/Cloud-CV/EvalAI-ngx/blob/master/README.md) for all the commands required to run tests etc.

**Comment by pavanrkadave** [comment]
No, I didn't run the tests on local.
Yeah sure! I will look into it. Thanks.

**Comment by RishabhJain2018** [comment]
Hi, @pavanrkadave Cna you please update the description, what this PR is supposed to fix.

**Comment by RishabhJain2018** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
