### PR TITLE
Fix #COC: Added Code of Conduct

### PR DESCRIPTION
**Pull request by sanyamdogra**
Addresses #72 
#### Changes proposed in this pull request:
Added the code of conduct for EvalAI-ngx.
-

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@sanyamdogra Can you please fix the Travis build so that we can merge this. The content looks good to me.

**Comment by sanyamdogra** [comment]
@RishabhJain2018 I don't know why the build is failing, should i change the target branch and then try?

**Comment by Shekharrajak** [comment]
@sanyamdogra ,  you need to update your branch with the latest upstream/master branch.

**Review by gautamjajoo — APPROVED** [review]
LGTM! @sanyamdogra Please update the branch after the Travis Build is fixed.

**Comment by RishabhJain2018** [comment]
Thanks @sanyamdogra for adding it.

**Pull request merged**
