### PR TITLE
Tests: Add unit tests for challenge evaluation component

### PR DESCRIPTION
**Pull request by Sanji515**
#### Changes proposed in this pull request:

- Added unit tests for the challenge evaluation component

- Increased coverage from 45% to 97%

- Link to live demo: http://pr-173-evalai.surge.sh

**<p align="center">Old code coverage**</p>

Screenshot from 2019-07-14 18-04-54

**<p align="center">Increased code coverage**</p>

Screenshot from 2019-07-16 15-35-08

### CODE REVIEW

**Comment by Sanji515** [comment]
@RishabhJain2018 @lunayach @galipremsagar @Shekharrajak 

Please review

**Comment by lunayach** [comment]
Why codecov has not commented yet? :sweat_smile:

**Comment by Sanji515** [comment]
May be it is not happy with the code coverage results lol :)

**Comment by Sanji515** [comment]
@lunayach I think we should restart the build

**Comment by lunayach** [comment]
Okay, restarted the build. Let's see.

**Review by lunayach — APPROVED** [review]
LGTM!

**Review by Shekharrajak — APPROVED** [review]

**Pull request merged**
