### PR TITLE
Fix #250  Fixed typo

### LINKED ISSUE #250: [docs] URL Structure section is unreadable
## I'm submitting a

(Check one with "x" from given options)
- [x] Bug report
- [ ] Feature request

## Current behavior

Links with the issue:
https://github.com/Cloud-CV/EvalAI-ngx/blob/master/.github/CODE_STRUCTURE.md#url-structure
The content under sections `Static Pages` and `Dynamic Pages` is quite difficult to read.

## Expected behavior

I think the data is supposed to be tables but doesn't appear so due to a minor typo. 

## Related screenshots

ngx-url-structure

## Other information

This might help: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

P.S. I would like to make a quick fix for this.

### PR DESCRIPTION
**Pull request by Suryansh5545**
#250 
Fixed the small typo which was making list unreadable Reported by @nikochiko.
Selection_022

### CODE REVIEW

**Comment by nikochiko** [comment]
@Suryansh5545 Thanks for the fix! Looks great :D 

But please try to ask on the issue before opening up the PRs. I had mentioned in the issue that 
>P.S. I would like to make a quick fix for this.

**Comment by Suryansh5545** [comment]
Sorry i forgot it i will close this pr

**Comment by nikochiko** [comment]
@Suryansh5545 No no, it's totally alright! Let it be there. 
I just meant you could tell on the issue that you want to work, so we both wouldn't be working on the same issue. It's alright 😄

**Comment by Suryansh5545** [comment]
Thx @nikochiko for understanding.

**Pull request closed without merging**
