### PR TITLE
Pre commit hook

### PR DESCRIPTION
**Pull request by sanketbansal**
#### Changes proposed in this pull request:

- Added pre-commit package for creating pre-commit hooks using package.json
- Added pre-commit hook for linitng

- Link to live demo: http://pr-165-evalai.surge.sh

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@lunayach @Shekharrajak @galipremsagar Can you please review this?

**Comment by lunayach** [comment]
@sanketbansal in a `.ts` file, I had created a lint error and then I tried to commit. It didn't do `ng lint` and hence no errors thus allowing me to commit. Can you please check if this is happening on your side also? (Mine lint error was replacing `'` with `"` in a string)

**Comment by Shekharrajak** [comment]
I think [this](https://github.com/angular/components/wiki/Pre-commit-hook-for-linters) will help.

**Review by Shekharrajak — COMMENTED** [review]
According to Angular's wiki page : https://github.com/angular/components/wiki/Pre-commit-hook-for-linters we can do it without adding new dependencies. Is there any other requirement to add this new dependency ?

**Comment by sanketbansal** [comment]
@Shekharrajak, **No** there is no other requirement to add this new dependency.

**Comment by Shekharrajak** [comment]
> According to Angular's wiki page : https://github.com/angular/components/wiki/Pre-commit-hook-for-linters we can do it without adding new dependencies. Is there any other requirement to add this new dependency ?

It looks like this is user cloned folder specific, can you try it once ?

**Comment by sanketbansal** [comment]
> > According to Angular's wiki page : https://github.com/angular/components/wiki/Pre-commit-hook-for-linters we can do it without adding new dependencies. Is there any other requirement to add this new dependency ?
> 
> It looks like this is user cloned folder specific, can you try it once ?

okay, working on it

**Comment by sanketbansal** [comment]
@lunayach, just remove .sample from pre-commit file and check.

**Comment by lunayach** [comment]
> @lunayach, just remove .sample from pre-commit file and check.

@sanketbansal which pre-commit file are you talking about?

**Comment by sanketbansal** [comment]
> > @lunayach, just remove .sample from pre-commit file and check.
> 
> @sanketbansal which pre-commit file are you talking about?

There will be a pre-commit file inside **.git/hooks** folder.

**Comment by lunayach** [comment]
I tried again with a new clone of Repository. `Pre-commit` file is getting auto-generated after `npm install`, so no worries there (and it's working). LGTM.

**Review by lunayach — APPROVED** [review]

**Review by galipremsagar — APPROVED** [review]

**Review by RishabhJain2018 — APPROVED** [review]

**Pull request merged**
