### PR TITLE
Load header and footer only once instead of on every page load

### PR DESCRIPTION
**Pull request by rlee80**
Moves header and footer loading to the main app component to improve performance. Now, the header and footer only need to be loaded once rather than on every component load.

- Link to live demo: http://pr-244-evalai.surge.sh 

-
image

image

image

### CODE REVIEW

**Comment by pushkalkatara** [comment]
Hi @rlee7 The build is failing, you can have a look [here](https://travis-ci.org/Cloud-CV/EvalAI-ngx/builds/627059790?utm_source=github_status&utm_medium=notification) for more details.

Also, please update the branch with the base branch.

**Comment by rlee80** [comment]
@pushkalkatara I looked over the Travis log but I can't find any errors that would be causing the build to fail. Could you help me investigate?

**Comment by pushkalkatara** [comment]
I think the build is failing due to - https://travis-ci.org/Cloud-CV/EvalAI-ngx/builds/627231842#L691

**Comment by Suryansh5545** [comment]
Hi @rlee7,
Sorry to interfere
 I saw your build and it is failing because of these error
Selection_034

The first error is shown because the typescript already now from the value that it is a boolen so there is no need to tell it specifically .

to fix this please change this => ` showNav: boolean = false; ` to this `showNav = false;`
and give a space in between bracket and curly bracket at line 53. so then it should look like this 
`if (event['url'] === '/auth' || event['url'] === '/dashboard') {   `


i folked your repo on my other git account and fixed the error and tested and it passed the test 

https://travis-ci.org/Divyansh5545/EvalAI-ngx/builds/627343238

**Comment by rlee80** [comment]
@Suryansh5545 Thanks! I appreciate the help. :)

**Review by Ram81 — APPROVED** [review]
@rlee7 LGTM

**Pull request closed without merging**
