### PR TITLE
UI fixes for login & sign up button on small screens

### PR DESCRIPTION
**Pull request by sanketbansal**
#### Changes proposed in this pull request:
- Fixed bug in header static nav for small and medium screens.
- Login and signup button bought in center.
- Fixed background image overflow bug.

Link to live demo: http://pr-113-evalai.surge.sh

### CODE REVIEW

**Comment by lunayach** [comment]
Hi @sanketbansal! Thanks for the Pull Request. Could you please attach a screenshot of the UI changes (i.e. in your case, for smaller and medium screens) in the PR description?

**Comment by sanketbansal** [comment]
header_before

#### Login and Sign up comes in center.

header_after

**Review by Shekharrajak — COMMENTED** [review]
Thanks for working on this issue. But isn't there is so much gap between right menu option button and the content on the homepage ? 

evalai-113

Did you try with various screensize devices through google dev tool ?

**Comment by sanketbansal** [comment]
> Thanks for working on this issue. But isn't there is so much gap between right menu option button and the content on the homepage ?
> 
> evalai-113
> 
> Did you try with various screensize devices through google dev tool ?

yeah, That is because the app is not responsive for smaller devices.
It's a seperate issue itself.

**Comment by sanketbansal** [comment]
https://github.com/Cloud-CV/EvalAI-ngx/pull/113#pullrequestreview-218093380

should i work on this bug in this PR?

**Comment by ACL19-Submission** [comment]
Hi! @sanketbansal As the title of PR is _login and sign up button alignment_, we expect the alignment to be good in all the devices. It would be better if this could be addressed in this PR itself.

**Comment by sanketbansal** [comment]
overflow

**Review by Shekharrajak — APPROVED** [review]
Thanks, it looks good to me.

**Comment by lunayach** [comment]
@sanketbansal it looks good to me as well. But please update the PR description with the surge deployment link and follow the PR description template properly. It's there whenever you open a new pull request.
And looking forward to your project proposal! :smile:

**Review by RishabhJain2018 — APPROVED** [review]

**Pull request merged**
