### PR TITLE
Removed vertical scrollbar from the modals

### PR DESCRIPTION
**Pull request by nikodembernat**
Google Code-in task: Remove the scroll from the modals.

#### Changes proposed in this pull request:

- Removed the "overflow-y" property from the base.scss

- Link to live demo: http://pr-220-evalai.surge.sh 

- On the left modal without "overflow-y: scroll", on the right with it. 
comparison

### CODE REVIEW

**Comment by Ram81** [comment]
@n-bernat can you test other modals in the project and share screenshots of few other modals that were fixed in PR description.

**Comment by nikodembernat** [comment]
- Update Profile
Update Profile

- Get your Auth Token
Get your Auth Token

- Change Password
Change Password

- Challenge Description
Challenge Description

- Phase Details (not affected by this change) 
Phase Details

**Review by lunayach — APPROVED** [review]
Looks good, LGTM! :tada:

**Review by Ram81 — APPROVED** [review]
@n-bernat LGTM. Nice work

**Pull request merged**
