### PR TITLE
Showing leaderboard precision value dynamically 

### LINKED ISSUE #284: Add option to change leader-board decimal precision
Add option under settings tab in challenge page to change leader-board decimal precision by challenge host (**Note:** settings tab is only for the host user).

It is expected to add the front-end to be able to show the current `leaderbord decimal precision` value (refer field [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/models.py#L328)) and to add the option to change this field by the host user.

### PR DESCRIPTION
**Pull request by Abhi58**
Fix #284  : Add option to change leader-board decimal precision

#### Changes proposed in this pull request:

Removed static leaderboard score value and added code to dynamically get the value from input box for precision value

http://pr-287-evalai.surge.sh 

-

### CODE REVIEW

**Comment by Abhi58** [comment]
TO be honest, I found difficulty in materialize css I think it is better to use bootstrap (yeah, I understand for this we need to change it in each page).

**Comment by Sanji515** [comment]
@Abhi58 Can you please fix the build?

And also why are there @Shekharrajak commits :arrow_down: 

Screenshot from 2020-02-12 01-15-46

**Comment by Abhi58** [comment]
Oh! It looks like because I cherry-pick few commits.

**Comment by RishabhJain2018** [comment]
> TO be honest, I found difficulty in materialize css I think it is better to use bootstrap (yeah, I understand for this we need to change it in each page).

Hi @Abhi58, What difficulty/issues did you find in materialize CSS?

**Pull request closed without merging**
