### PR TITLE
Add feature to filter the submissions by team name in view all submission

### PR DESCRIPTION
**Pull request by Sanji515**
#### Changes proposed in this pull request:

- Added the input box to get the filter query as participant team name

- Used the all challenge submission API with filter query for filtering the submissions

- Link to live demo: http://pr-167-evalai.surge.sh

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@Sanji515 Please remove the conflicts here.

**Comment by Sanji515** [comment]
@RishabhJain2018 I'll resolve these and in view all submissions PR once #164 gets merged

**Comment by lunayach** [comment]
@Sanji515  Now since #164 is merged, resolve the conflicts and pass the build.

**Comment by Sanji515** [comment]
@lunayach Please review

**Review by galipremsagar — COMMENTED** [review]
Code changes seem fine but there seems to be some issue in functionality, taking it offline.

**Review by galipremsagar — COMMENTED** [review]
I'm somehow inclined towards doing this filtering on front-end itself rather than a back-end api call. The cost of this would be a round-trip communication so why not lets use the data in the front-end itself?

**Comment by lunayach** [comment]
> I'm somehow inclined towards doing this filtering on front-end itself rather than a back-end api call. The cost of this would be a round-trip communication so why not lets use the data in the front-end itself?

@galipremsagar  Yes, this makes sense! Fetch all the submissions/team-names for once, then in front-end, manipulate (in this case, filter) based on the needs (in this case, search-query).

**Comment by galipremsagar** [comment]
> > I'm somehow inclined towards doing this filtering on front-end itself rather than a back-end api call. The cost of this would be a round-trip communication so why not lets use the data in the front-end itself?
> 
> @galipremsagar Yes, this makes sense! Fetch all the submissions/team-names for once, then in front-end, manipulate (in this case, filter) based on the needs (in this case, search-query).

@lunayach  @RishabhJain2018 just spoke to @Sanji515 on this. Since we have pagination in place we have to do back-end api call. I think either we will have to get rid of back-end based pagination and turn it into purely a front-end pagination or live with filtering using back-end API having an overhead of single round-trip communication. I'm okay with merging this PR but we will have to decide on this moving forward.

**Review by galipremsagar — APPROVED** [review]

**Comment by RishabhJain2018** [comment]
> I'm somehow inclined towards doing this filtering on front-end itself rather than a back-end api call.
Yes, this makes sense and we should try to have it after the initial release. 

@Sanji515 Can you please open up an issue to keep track of it?

**Pull request merged**
