### PR TITLE
Add feature for challenge host to toggle the submission flag status

### PR DESCRIPTION
**Pull request by Sanji515**
#### Changes proposed in this pull request:

- Added a new settings option in the menu for flag/unflag the submission

- Given a modal for confirmation before the change

- Link to live demo: http://pr-174-evalai.surge.sh

**Screenshot:**

Screenshot from 2019-07-17 02-22-39

### CODE REVIEW

**Comment by Sanji515** [comment]
@lunayach @RishabhJain2018 @galipremsagar @Shekharrajak 

Please review

**Comment by Shekharrajak** [comment]
Can you please post few screenshots for Unsuccessful attempts (the error message) and successful attempts ? I think the option should be either Public (why it is named unflagged) or Private right?

**Comment by RishabhJain2018** [comment]
Hey @Shekharrajak  Flagging is different from public/private. Flagging is used when a participant team is found cheating and the challenge host can flag their submissions.

**Comment by Shekharrajak** [comment]
Okay cool! Thanks for letting me know this point.

**Comment by lunayach** [comment]
@Sanji515 resolve the conflicts.

**Review by lunayach — APPROVED** [review]
The functionality and code looks good to me.

**Pull request merged**
